### ISSUE TITLE
Messaging Error

### ISSUE THREAD

**Issue by les-bres** [IsaacGluck/Tutee#29]
When I tried to log in I got this error bc of the messaging feature.  Fix before you merge with master pls!!

![screen shot 2015-01-24 at 9 23 11 am](https://cloud.githubusercontent.com/assets/5796465/5887628/b2624940-a3aa-11e4-910d-75ece944b255.png)

**Comment by CobyGoldbergs** [comment]
The error, I'm going to guess, is because you're trying to login with an account made before I made these changes. That means it wasn't made with a 'conversations' key (or a username for that matter). You'll need to run db.tutors.remove() and tb.tutees.remove(), and start again with new users. That's how it works every time changes are made to what keys the users have.

**Comment by les-bres** [comment]
ah gotchu
